version: 2.1
orbs:
  snyk: snyk/snyk@0.0.9
# Containerize codebase, checkout code, 
# install npm packages, run Snyk on docker container
jobs:
  build:
    working_directory: ~/application_security_data_visualizations
    docker:
      - image: 'circleci/node:4.8.2'
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install  
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-container'
          fail-on-issues: false
          monitor-on-build: true
          protect: true
          token-variable: SNYK_AUTH
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: org-global